/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class snw_test_MP3ToWAV */

#ifndef _Included_snw_test_MP3ToWAV
#define _Included_snw_test_MP3ToWAV
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     snw_test_MP3ToWAV
 * Method:    decode_mp3
 * Signature: (Ljava/lang/String;Lsnw/test/MP3ToWAV/Mp3Info;)Z
 */
JNIEXPORT jboolean JNICALL Java_snw_test_MP3ToWAV_decode_1mp3
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
