/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class snw_test_IconDance */

#ifndef _Included_snw_test_IconDance
#define _Included_snw_test_IconDance
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     snw_test_IconDance
 * Method:    getDesktopHWND
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_snw_test_IconDance_getDesktopHWND
  (JNIEnv *, jclass);

/*
 * Class:     snw_test_IconDance
 * Method:    getIconNum
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_snw_test_IconDance_getIconNum
  (JNIEnv *, jclass, jint);

/*
 * Class:     snw_test_IconDance
 * Method:    setIconPos
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_snw_test_IconDance_setIconPos
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     snw_test_IconDance
 * Method:    getSize
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_snw_test_IconDance_getSize
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
