/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class snw_test_PureMP3Decoder */

#ifndef _Included_snw_test_PureMP3Decoder
#define _Included_snw_test_PureMP3Decoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     snw_test_PureMP3Decoder
 * Method:    decodeMp3
 * Signature: (Ljava/lang/String;Lsnw/test/PureMP3Decoder/Mp3Info;)Z
 */
JNIEXPORT jboolean JNICALL Java_snw_test_PureMP3Decoder_decodeMp3
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
